# coding: utf-8

"""
    Demo Service - Internal API

    내부 서비스 간 통신을 위한 API 명세 (비공개)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from internal_api_client.models.internal_user_response import InternalUserResponse

class TestInternalUserResponse(unittest.TestCase):
    """InternalUserResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalUserResponse:
        """Test InternalUserResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalUserResponse`
        """
        model = InternalUserResponse()
        if include_optional:
            return InternalUserResponse(
                id = '2',
                name = 'user1',
                email = 'user1@example.com',
                role = 'user',
                profile_image_url = 'http://localhost:8081/path/to/image.png',
                last_active_at = 1678886400000,
                updated_at = 1678886400000,
                created_at = 1678886400000
            )
        else:
            return InternalUserResponse(
                id = '2',
                name = 'user1',
                email = 'user1@example.com',
                role = 'user',
                profile_image_url = 'http://localhost:8081/path/to/image.png',
                last_active_at = 1678886400000,
                updated_at = 1678886400000,
                created_at = 1678886400000,
        )
        """

    def testInternalUserResponse(self):
        """Test InternalUserResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
