# coding: utf-8

"""
    Demo Service - Internal API

    내부 서비스 간 통신을 위한 API 명세 (비공개)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from internal_api_client.api.internal_user_api import InternalUserApi


class TestInternalUserApi(unittest.IsolatedAsyncioTestCase):
    """InternalUserApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = InternalUserApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_internal_user_by_email(self) -> None:
        """Test case for get_internal_user_by_email

        이메일로 내부 사용자 정보 조회
        """
        pass

    async def test_get_internal_user_by_id(self) -> None:
        """Test case for get_internal_user_by_id

        사용자 ID로 내부 사용자 정보 조회
        """
        pass


if __name__ == '__main__':
    unittest.main()
