# coding: utf-8

# flake8: noqa
"""
    Demo Service - Internal API

    내부 서비스 간 통신을 위한 API 명세 (비공개)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from internal_api_client.models.error_response import ErrorResponse
from internal_api_client.models.internal_user_response import InternalUserResponse
