name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set IMAGE_TAG
        id: tag
        run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)-${{ github.run_number }}" >> $GITHUB_ENV

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push Docker image to Harbor
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/open-webui-backend:${{ env.IMAGE_TAG }}
            ${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/open-webui-backend:latest

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Checkout k8s-config Repository
        uses: actions/checkout@v4
        with:
          repository: edu-ide/k8s-config
          path: k8s-config
          token: ${{ secrets.TARGET_REPO_TOKEN }}

      - name: Update values.yaml
        env:
          IMAGE_PULL_REPOSITORY: ${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/open-webui-backend
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          SERVICE_NAME: openwebui
        run: |
          cd k8s-config
          yq eval '.${{ env.SERVICE_NAME }}.repository = env(IMAGE_PULL_REPOSITORY)' -i values.yaml
          yq eval '.${{ env.SERVICE_NAME }}.tag = env(IMAGE_TAG)' -i values.yaml
          yq eval '.${{ env.SERVICE_NAME }}.imagePullSecrets = [{"name":"harbor-cred"}]' -i values.yaml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add values.yaml
          git commit -m "Update ${{ env.SERVICE_NAME }} image to ${{ env.IMAGE_PULL_REPOSITORY }}:${{ env.IMAGE_TAG }}"
          git push origin main
